In [3]:
import numpy as np
import pandas as pd

In [6]:
data = pd.read_csv('clean5.csv', delimiter=',')

E:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [7]:
data

,Unnamed: 0,district,rural,stratum_code,age,marital_status,delivered_any_baby,born_alive_female,born_alive_male,born_alive_total,...,no_of_times_conceived,age_at_first_conception,is_injectable_contraceptive,health_prob_afters_fp_use,counselled_for_menstrual_hyg,aware_abt_haf,aware_abt_ort_ors,aware_abt_ort_ors_zinc,aware_abt_danger_signs_new_born,iscoveredbyhealthscheme
0,0,13,1,2,42,3,1,2,1,3,...,3,18,2,2,2,1,1,2,2,2
1,1,13,1,2,47,3,1,3,3,6,...,7,17,2,-1,2,1,1,2,2,2
2,2,13,1,2,32,3,1,2,2,4,...,6,19,1,-1,2,1,1,2,2,2
3,3,13,1,2,20,3,1,1,0,1,...,2,17,2,-1,1,1,1,2,2,1
4,4,13,1,2,27,3,1,0,3,3,...,3,19,1,2,1,1,1,2,2,1
5,5,13,1,2,29,3,1,3,2,5,...,6,20,1,2,1,1,1,2,2,1
6,6,13,1,2,26,3,1,0,1,1,...,1,21,1,2,2,1,1,2,2,2
7,7,13,1,2,26,3,1,2,1,3,...,4,18,1,-1,1,1,1,2,2,2
8,8,13,1,2,30,3,1,1,1,2,...,2,18,2,-1,2,1,1,2,2,2
9,9,13,1,2,40,3,1,4,3,7,...,7,18,2,-1,2,1,1,2,2,2
10,10,13,1,2,40,4,1,2,2,4,...,4,20,2,-1,2,1,1,2,2,2
11,11,13,1,2,47,3,1,4,6,10,...,10,18,1,-1,2,1,1,2,2,2
12,12,13,1,2,39,3,1,2,1,3,...,3,22,2,-1,2,1,1,2,1,1
13,13,13,1,2,42,5,1,1,4,5,...,5,16,-1,-1,2,2,2,2,2,2
14,14,13,1,2,38,3,1,0,2,2,...,2,19,1,-1,2,1,1,2,2,2
15,15,13,1,2,32,3,1,3,1,4,...,6,20,1,2,2,1,1,2,2,2
16,16,13,1,2,28,3,1,0,1,1,...,3,18,1,2,2,1,1,2,2,2
17,17,13,1,2,22,3,1,0,1,1,...,2,19,1,-1,1,1,1,2,2,2
18,18,13,1,2,19,3,2,0,0,0,...,1,19,2,-1,2,1,1,2,2,2
19,19,13,1,2,32,3,1,3,2,5,...,5,20,1,-1,1,1,1,2,2,2
20,20,13,1,2,34,5,1,2,2,4,...,4,21,-1,-1,2,2,2,2,2,2
21,21,13,1,2,47,3,1,6,3,9,...,10,19,1,-1,2,1,1,2,2,2
22,22,13,1,2,25,3,1,0,1,1,...,2,21,1,-1,1,1,1,2,1,2
23,23,13,1,2,38,5,1,3,1,4,...,4,20,-1,-1,2,2,2,2,2,2
24,24,13,1,2,23,3,1,1,1,2,...,3,22,1,-1,2,1,1,2,2,2
25,25,13,1,2,37,3,1,2,6,8,...,8,22,1,-1,2,2,1,2,2,2
26,26,13,1,2,40,3,1,1,2,3,...,3,17,1,2,2,1,1,2,2,2
27,27,13,1,2,34,3,1,2,2,4,...,4,18,1,2,2,1,1,2,2,2
28,28,13,1,2,32,3,1,1,2,3,...,3,20,1,2,1,1,1,1,2,2
29,29,13,1,2,29,3,1,0,3,3,...,3,22,1,2,2,1,1,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
905947,941101,2,2,0,44,3,1,1,4,5,...,5,18,1,-1,2,1,1,2,1,2
905948,941102,2,2,0,24,3,2,-1,-1,-1,...,1,24,1,2,2,1,1,2,1,2
905949,941103,2,2,0,27,3,1,2,0,2,...,3,22,1,-1,2,1,1,2,1,2
905950,941104,2,2,0,45,3,1,1,2,3,...,3,23,1,-1,2,1,1,2,1,2
905951,941105,2,2,0,49,3,1,2,1,3,...,3,18,2,-1,1,1,1,2,1,2
905952,941106,2,2,0,24,3,1,1,0,1,...,2,22,1,-1,1,1,1,2,1,2
905953,941107,2,2,0,36,3,1,1,1,2,...,4,26,1,-1,1,1,1,2,1,2
905954,941108,2,2,0,38,3,1,3,2,5,...,7,18,2,-1,1,1,1,1,1,2
905955,941109,2,2,0,45,3,1,4,1,5,...,5,17,1,-1,1,1,1,2,1,2
905956,941110,2,2,0,41,3,1,3,1,4,...,4,16,2,-1,2,1,1,1,1,1
905957,941111,2,2,0,48,3,1,1,0,1,...,1,23,2,-1,1,1,1,2,1,2
905958,941112,2,2,0,39,3,1,1,2,3,...,3,21,2,-1,1,1,1,2,1,2
905959,941113,2,2,0,36,3,1,3,1,4,...,4,21,2,-1,1,1,1,2,1,1
905960,941114,2,2,0,30,3,1,0,1,1,...,1,17,2,-1,1,1,1,2,1,2
905961,941115,2,2,0,33,3,1,1,2,3,...,3,16,2,-1,1,1,1,2,1,2
905962,941116,2,2,0,49,3,1,0,2,2,...,2,23,2,-1,1,1,1,2,1,2
905963,941117,2,2,0,39,3,1,0,2,2,...,2,17,2,-1,1,1,1,2,1,2
905964,941118,2,2,0,39,3,1,1,1,2,...,2,24,2,-1,1,1,1,2,1,2
905965,941119,2,2,0,39,3,1,2,2,4,...,4,24,2,-1,1,1,1,2,1,2
905966,941120,2,2,0,42,3,1,1,3,4,...,4,17,2,-1,1,1,1,2,1,2
905967,941121,2,2,0,44,3,1,1,3,4,...,4,18,2,-1,2,1,1,1,1,2
905968,941122,2,2,0,23,3,2,-1,-1,-1,...,1,23,1,-1,2,1,1,1,1,3
905969,941123,2,2,0,37,3,1,1,1,2,...,2,19,1,-1,2,1,1,1,1,2
905970,941124,2,2,0,27,3,1,0,1,1,...,1,25,1,2,2,1,1,1,1,2
905971,941125,2,2,0,49,3,1,2,2,4,...,4,25,2,-1,2,1,1,1,1,1
905972,941126,2,2,0,36,3,1,2,4,6,...,6,19,1,-1,2,1,1,1,1,2
905973,941127,2,2,0,39,3,1,2,1,3,...,3,15,2,-1,2,1,1,2,1,2
905974,941128,2,2,0,41,3,1,1,2,3,...,3,22,-1,-1,2,2,2,2,2,2
905975,941129,2,2,0,38,3,1,1,1,2,...,2,22,2,-1,2,1,1,2,1,2
905976,941130,2,2,0,43,3,1,1,1,2,...,2,19,1,-1,2,1,1,1,1,2

In [13]:
sum(data["district"]==13)

29869

In [28]:
data["district"] = data["district"].replace([13], "HARIDWAR")

In [29]:
data["district"]

0         HARIDWAR
1         HARIDWAR
2         HARIDWAR
3         HARIDWAR
4         HARIDWAR
5         HARIDWAR
6         HARIDWAR
7         HARIDWAR
8         HARIDWAR
9         HARIDWAR
10        HARIDWAR
11        HARIDWAR
12        HARIDWAR
13        HARIDWAR
14        HARIDWAR
15        HARIDWAR
16        HARIDWAR
17        HARIDWAR
18        HARIDWAR
19        HARIDWAR
20        HARIDWAR
21        HARIDWAR
22        HARIDWAR
23        HARIDWAR
24        HARIDWAR
25        HARIDWAR
26        HARIDWAR
27        HARIDWAR
28        HARIDWAR
29        HARIDWAR
            ...
905947     CHAMOLI
905948     CHAMOLI
905949     CHAMOLI
905950     CHAMOLI
905951     CHAMOLI
905952     CHAMOLI
905953     CHAMOLI
905954     CHAMOLI
905955     CHAMOLI
905956     CHAMOLI
905957     CHAMOLI
905958     CHAMOLI
905959     CHAMOLI
905960     CHAMOLI
905961     CHAMOLI
905962     CHAMOLI
905963     CHAMOLI
905964     CHAMOLI
905965     CHAMOLI
905966     CHAMOLI
905967     CHAMOLI
905968     CHAMOLI
905969     CHAMOLI
905970     CHAMOLI
905971     CHAMOLI
905972     CHAMOLI
905973     CHAMOLI
905974     CHAMOLI
905975     CHAMOLI
905976     CHAMOLI
Name: district, Length: 905977, dtype: object

In [59]:
data["chew_updated"] = data["chew"]

In [61]:
data["chew_updated"] = data["chew_updated"].replace([1, 3, 5], "Chew with Tobacco")
data["chew_updated"] = data["chew_updated"].replace([2, 4], "Chew without Tobacco")
data["chew_updated"] = data["chew_updated"].replace([0, 6, 7, 8], 8)

In [62]:
data["chew_updated"].unique()

array([8, 'Chew with Tobacco', 'Chew without Tobacco'], dtype=object)

In [63]:
data.to_csv('clean5.csv')

In [50]:
sum(data["chew_updated"]==1)

7427

In [52]:
data["rural"] = data["rural"].replace([2], "Urban")

In [57]:
data = data.drop(["chew_updated"], axis = 1)

In [65]:
data["smoke_updated"] = data["smoke"]
data["alcohol_updated"] = data["alcohol"]

In [69]:
sum(data["smoke"]==4)

774850